version: "3"
services:

    StarTrek:
        image: blooomberg/trek_bot
        build:
            context: .
            dockerfile: ./Dockerfile
        links:
            - mongo
        restart: always

    mongo:
        image: mongo:3.6
        restart: always
        ports:
            - 8081:8081
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
