version: "3"
services:

    StarTrek:
        image: ghcr.io/simonborin/trek_bot:${GAME_VERSION:-latest}
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                GAME_VERSION: ${GAME_VERSION:-development}
        links:
            - mongo
        restart: always


    mongo:
        image: mongo:3.6
        restart: always
        ports:
            - 27017:27017
