version: "3"
services:

    StarTrek:
        image: blooomberg/trek_bot
        build:
            context: .
            dockerfile: ./Dockerfile
        links:
            - mongo
        restart: always

    mongo:
        image: mongo:3.6
        restart: always

